### ISSUE TITLE
php 8.1 deprecations

### ISSUE THREAD

**Issue by Selion05** [adbario/php-dot-notation#25]
Hey, on 8.1 I get a few deprecations  like 

> Deprecated: Return type of Adbar\Dot::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

- ArrayAccess::offsetExists(mixed $offset): bool
- ArrayAccess::offsetGet(mixed $offset): mixed
- ArrayAccess::offsetSet(mixed $offset, mixed $value): void
- ArrayAccess::offsetUnset(mixed $offset): void
- Countable::count(): int
- IteratorAggregate::getIterator(): Traversable
- JsonSerializable::jsonSerialize(): mixed

can we add the `ReturnTypeWillChange` attribute?

**Comment by Ethorsen** [comment]
This should be taken care of in this PR https://github.com/adbario/php-dot-notation/pull/22
