### ISSUE TITLE
Replace (more specifically replace recursive)

### ISSUE THREAD

**Issue by mattsah** [adbario/php-dot-notation#7]
I notice there's a `merge()` function, which of course is quite useful, although it doesn't look like it does so recursively.  I'm wondering if there would be any support for adding a `replace()` function using PHP's `array_replace()`  similarly.

Lastly, and most useful, I believe,  `mergeRecursive()` and `replaceRecursive()`.

**Comment by enobrev** [comment]
I've been using the version from this PR for `mergeRecursive` and `mergeRecursiveDistinct`, which both work great, and I'm hoping will be accepted at some point.

https://github.com/adbario/php-dot-notation/pull/3

**Comment by adbario** [comment]
PR for `mergeRecursive` and `mergeRecursiveDistinct` methods is now merged and also `replace`method is added.
