### ISSUE TITLE
Add __set_state() for var_export() support

### ISSUE THREAD

**Issue by mattsah** [adbario/php-dot-notation#8]
Using var export to export executable PHP into a cache file is good for performance, especially if the collection is being packed with lots of data from lots of config files.  I'd like to be able to export the whole collection and restore... should be as simple as:

```php
static public function __set_state($data)
{
    return new static($data['items']);
}
```

**Comment by acrois** [comment]
Good idea, you can make the pull request with this code to get credit for it! 👍
